### ISSUE TITLE
ERR_BUFFER_OUT_OF_BOUNDS in buffer.js

### ISSUE THREAD

**Issue by AitorIriondo** [xsens/xsens_dot_server#33]
Hello!

I have been running the server several times without any issue, however, today when I wanted to run it again I got the following error:

```
xsens_dot_server>node xsensDotServer
Web GUI Handler instantiated
BLE Handler started.
Webserver listening on port 8080, IP address: 10.10.64.131
internal/buffer.js:75
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer b
ounds
←[90m    at boundsError (internal/buffer.js:75:11)←[39m
←[90m    at Buffer.readUInt8 (internal/buffer.js:243:5)←[39m
    at Hci.processCmdCompleteEvent (C:\Users\iria\xsens_dot_server\node_modules\
←[4mnoble←[24m\lib\hci-socket\hci.js:566:25)
    at Hci.onSocketData (C:\Users\iria\xsens_dot_server\node_modules\←[4mnoble←[
24m\lib\hci-socket\hci.js:461:12)
←[90m    at BluetoothHciSocket.emit (events.js:310:20)←[39m
    at BluetoothHciSocket.onHciEventEndpointData (C:\Users\iria\xsens_dot_server
\node_modules\←[4mbluetooth-hci-socket←[24m\lib\usb.js:156:10)
←[90m    at InEndpoint.emit (events.js:310:20)←[39m
    at Transfer.transferDone (C:\Users\iria\xsens_dot_server\node_modules\←[4mus
b←[24m\usb.js:441:9) {
  code: ←[32m'ERR_BUFFER_OUT_OF_BOUNDS'←[39m
```

I have not changed the network, device or sensors, neither the drivers nor any configuration from yesterday. Any ideas of how to solve it?

Thanks!

**Comment by AitorIriondo** [comment]
I made it work again with some steps. For those wondering why the server stops working after several days of use in Windows 7, it can be that the driver installed by using Zadig gets corrupted. To solve it, go to Device Manager, update the driver, and it will return to be your usual Bluetooth driver. Restart the computer, reinstall with Zadig, and restart the computer again. Finally update again the driver with Zadig, and now it should work.
