### ISSUE TITLE
Error: Cannot find module 'bluetooth-hci-socket' in Raspberry Pi 4B

### ISSUE THREAD

**Issue by rogergallart** [xsens/xsens_dot_server#43]
Hi
I am trying to install and run Xsens Dot Server in a Raspberry 4B (with Raspberry OS bullseye).
When I run the program:

```
sudo node xsensDotServer
```
I get this error:

```
Web GUI Handler instantiated
module.js:549
    throw err;
    ^

Error: Cannot find module 'bluetooth-hci-socket'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/armtracker/xsens_server/xsens_dot_server/node_modules/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Any idea on how to fix this ? I guess that some library is missing or was not installed correctly (I got several deprecation warnings through the installation process and other warnings), but I don't know how to debug this. Any help will be appreciated.

Thanks in advance

**Comment by Alix-Chadwell** [comment]
I am seeing this exact same error. It seems like the libraries are referring to out of date links or something. I'd also be grateful for any guidance on how to fix this or an updated version of the code. I am using a PiTop OS which is also based on  Raspberry OS Bullseye.

**Comment by rogergallart** [comment]
> I am seeing this exact same error. It seems like the libraries are referring to out of date links or something. I'd also be grateful for any guidance on how to fix this or an updated version of the code. I am using a PiTop OS which is also based on Raspberry OS Bullseye.

Hi Alix. Just to let you know that I contacted Xsense and they say they no longer provide support for this software. So don't expect any reply from their side. This was their reply:

> [Data Server ](https://github.com/xsens/xsens_dot_server)is the only available example to connect DOTs to the laptop or Rasberry Pi, but, unfortunately, it is not updated and we don't provide support for it.

Best regards

**Comment by mcrooks83** [comment]
Hi, 

you could try this https://github.com/mcrooks83/rs-sensor-server

(its a remake of this same server that I have running on raspberry pi w) 

works with docker and standalone
